library(amaryaml)
library(knitr)
library(kableExtra)
library(pander)
library(DiagrammeR)
library(DiagrammeRsvg)
library(rsvg)

panderOptions('table.style', 'grid')
panderOptions('table.alignment.default', 'left')
panderOptions('table.split.table', Inf)
panderOptions('keep.line.breaks', TRUE)
panderOptions('use.hyphening', TRUE)

opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, cache = TRUE, dev = 'tikz')
